### PR TITLE
Add swap fee info to trade chart and table

### PR DESCRIPTION
**Pull request by AlexTheLion123**
- add trading fee to buy/sell text labels on charts (works for backtesting)

### CODE REVIEW

**Comment by AlexTheLion123** [comment]
This PR, along with #165 , fixes #166

**Comment by AlexTheLion123** [comment]
fixes #161

**Comment by AlexTheLion123** [comment]
TODO: add fee to trade table

**Comment by AlexTheLion123** [comment]
Have added `total swap fees` to the trade table as well

**Review by miohtama — APPROVED** [review]

**Comment by AlexTheLion123** [comment]
@miohtama 
Screenshot from 2023-01-05 14-49-00

Screenshot from 2023-01-05 14-49-07

**Pull request merged**
